Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@aezazali1997 
aezazali1997
/
portfolio
Public
1
00
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
portfolio/.github/workflows/deno.yml
@aezazali1997
aezazali1997 updated the file
Latest commit 8e52c42 on Jun 11
 History
 1 contributor
55 lines (48 sloc)  1.7 KB
   
# This is a basic workflow to help you get started with Actions

name: Deploy react app

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Node
      - name: install node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12
      # Install Yarn
      - name: install YARN
        uses: borales/actions-yarn@v2.0.0
        with:
         cmd: install
       #build vue app with yarn
      - name: build vue app
        run: sudo yarn build
       # install surge
      - name: install surge
        run: npm install -g surge
         # run surge
      - name: run surge
        run: surge ./build vue-cowboy-app.surge.sh --token ${{secrets.SURGE_TOKEN}}     
          
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
